url:                http://peaceofmindsf.net
title:            Peace of Mind
name:            Peace of Mind
owner:
  name:           Tim Richards
  email:          sifutimr@gmail.com
  conversion:     https://peace_of_mind.herokuapp.com

timezone:    America/Los_Angeles
future:      true
highlighter:  pygments
markdown:    redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink:   /:categories/:title/

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

sass:
  sass_dir: _scss

include: [".htaccess"]
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems, config, log, Rakefile, Rakefile.rb, tmp, less, spec, package.json, node_modules]

gems:
  ['bootstrap-sass', 'jekyll-assets']

assets:
  compress:
    css: false
    js: false
  autowrite: true
  cache: false
  cache_type: filesystem
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: false

  assets:
    - "*.png"
    - "bundle.css"

  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js

  features:
    liquid: false
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true
